export const AUTHENTICATE_START = "AUTHENTICATE_START"
export const AUTHENTICATE_USER = "AUTHENTICATE_USER"
export const LOGGED_OUT_USER = "LOGGED_OUT_USER"
export const CHECK_AUTH_STATUS = 'CHECK_AUTH_STATUS';
