export const NEXT_STEP = 'NEXT_STEP'
export const PREVIOUS_STEP = 'PREVIOUS_STEP'
export const RESET_STEP = 'RESET_STEP'


// team api related 

export const CREATED_TEAM_TYPE = 'CREATED_TEAM_TYPE'
export const FETCHING_TEAM_TYPE = 'FETCHING_TEAM_TYPE'
export const FETCHING_SINGLE_TEAM_TYPE = 'FETCHING_SINGLE_TEAM_TYPE'
export const UPDATE_SINGLE_TEAM_TYPE = 'UPDATE_SINGLE_TEAM_TYPE'
export const ASSIGN_A_MEMBER_TYPE = 'ASSIGN_A_MEMBER_TYPE'
export const UNASSIGN_A_MEMBER_TYPE = 'UNASSIGN_A_MEMBER_TYPE'